# Generated by Django 5.2.1 on 2025-06-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
